<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="MAIN" Id="{d25881fd-bae0-4e0a-b3eb-c173027ef094}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[.Global_Variables.TcJoy(); // Read HMI data

IF .Global_Variables.TcJoy.bIsActive THEN // if HMI is connected
	;
END_IF

p_FaultMonitoring(); // Check fault routine
//inputs
//Seq
//Outputs
//logging
//recipe system]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="3" Count="3" />
      <LineId Id="2" Count="0" />
      <LineId Id="11" Count="0" />
      <LineId Id="10" Count="0" />
      <LineId Id="12" Count="0" />
      <LineId Id="14" Count="3" />
    </LineIds>
  </POU>
</TcPlcObject>