<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="P_SequenceReader" Id="{b7f6e06f-02ce-4bed-9da9-aa8070aed894}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_SequenceReader
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//best effort servo follower.
//Elapsed time
//each time signature gets a value in mm for it's position relative to the 0 point of the system.
//buffer 3 seconds worth of data?
]]></ST>
    </Implementation>
    <LineIds Name="P_SequenceReader">
      <LineId Id="5" Count="1" />
      <LineId Id="8" Count="1" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>